services:
  database:
    image: mysql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

pipeline:
  build:
    image: kszucs/miniconda3
    environment:
      - MYSQL_HOST=database
    commands:
      - sleep 10  # wait for mysql to start
      - python setup.py test

  # pypi:
  #   repository: https://pypi.python.org/pypi
  #   username: ${PYPI_USERNAME}
  #   password: ${PYPI_PASSWORD}
  #   distributions:
  #     - sdist
  #   when:
  #     event: [tag]
